name: Cherry-pick commits into release branches if needed

on:
  pull_request_target:
    branches:
      - main
    types: [closed]

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  cherry-pick:
    name: Cherry-pick commits into release branches
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          label_pattern: ^cherry-pick (release\/v[^ ]+)$
          merge_commits: skip
          branch_name: cherry-pick/${pull_number}-to-${target_branch}
          pull_title: "🍒 [cherry-pick into ${target_branch}] ${pull_title}"
          copy_assignees: true
          copy_labels_pattern: .*
          copy_requested_reviewers: true
